services:
  downloader:
    build: .
    container_name: openmedia-downloader
    env_file: .env
    ports:
      - "18080:8080"   # SABnzbd Web UI (für Debugging)
    volumes:
      - downloads:/downloads
      - config:/config

volumes:
  downloads:
  config:
